In [1]:
import jax
import jax.numpy as jnp
from jax.experimental import sparse

# Create a dense matrix as an example
dense_matrix = jnp.array([
    [0, 0, 1, 0],
    [0, 0, 0, 0],
    [0, 2, 0, 3],
    [0, 0, 0, 4]
])

# Convert to BCOO format
sparse_matrix = sparse.BCOO.fromdense(dense_matrix)

# Convert back to dense format
dense_from_sparse = sparse_matrix.todense()

print("Original Dense Matrix:")
print(dense_matrix)

print("\nSparse Matrix (BCOO) converted back to Dense:")
print(dense_from_sparse)


Original Dense Matrix:
[[0 0 1 0]
 [0 0 0 0]
 [0 2 0 3]
 [0 0 0 4]]

Sparse Matrix (BCOO) converted back to Dense:
[[0 0 1 0]
 [0 0 0 0]
 [0 2 0 3]
 [0 0 0 4]]


In [2]:
import jax.numpy as jnp
from jax.experimental.sparse.linalg import spsolve

# A = [[4, 1, 0],
#      [1, 3, 1],
#      [0, 1, 2]]
# Represent A in CSR format:

# data: non-zero values
data = jnp.array([4, 1, 1, 3, 1, 1, 2], dtype=jnp.float32)
# indices: column indices of non-zero values
indices = jnp.array([0, 1, 0, 1, 2, 1, 2], dtype=jnp.int32)
# indptr: row pointers (cumulative count of nonzeros per row)
indptr = jnp.array([0, 2, 5, 7], dtype=jnp.int32)

# right-hand side
b = jnp.array([1.0, 2.0, 3.0], dtype=jnp.float32)

# solve Ax = b
x = spsolve(data, indices, indptr, b)

# print result
print("Solution x =", x)

Solution x = [0.22222224 0.11111104 1.4444445 ]
